In [ ]:
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [ ]:
df = pd.read_csv("data/students.csv")
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [3]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
X = df.drop("math_score", axis=1)
y = df["math_score"]

In [5]:
X

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,99,95
996,male,group C,high school,free/reduced,none,55,55
997,female,group C,high school,free/reduced,completed,71,65
998,female,group D,some college,standard,completed,78,77
999,female,group D,some college,free/reduced,none,86,86

In [6]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [ ]:
numerical_features = X.select_dtypes(exclude="object").columns
categorical_features = X.select_dtypes(include="object").columns

C:\Users\Shreyansh_2\AppData\Local\Temp\ipykernel_4216\2647891575.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(include='object').columns

In [8]:
numerical_features

Index(['reading_score', 'writing_score'], dtype='str')

In [9]:
categorical_features

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='str')

In [ ]:
ohe = OneHotEncoder(drop="first")
scaler = StandardScaler()

In [ ]:
preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", ohe, categorical_features),
        ("StandardScaler", scaler, numerical_features),
    ]
)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [13]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [14]:
X_train.shape

(750, 14)

In [15]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_scr = r2_score(true, predicted)

    return mae, mse, rmse, r2_scr

In [20]:
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "KNeighborsRegressor": KNeighborsRegressor(),
    "DecisionTreeRegressor": DecisionTreeRegressor(),
    "RandomForestRegressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(),
    "AdaBoostRegressor": AdaBoostRegressor(),
    "CatBoostRegressor": CatBoostRegressor(),
    "SVR": SVR()
}

models_list = []
r2_list = []

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    ## make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    ## Evaluate train and test datasets
    train_mae, train_mse, train_rmse, train_r2_scr = evaluate_model(
        y_train, y_train_pred
    )
    test_mae, test_mse, test_rmse, test_r2_scr = evaluate_model(y_test, y_test_pred)

    print(list(models.values())[i])
    models_list.append(list(models.keys())[i])

    print("Model performance for Training set")
    print("- Root Mean Squared Error: {:.4f}".format(train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(train_mae))
    print("- R2 Score: {:.4f}".format(train_r2_scr))

    print("----------------------------------")

    print("Model performance for Test set")
    print("- Root Mean Squared Error: {:.4f}".format(test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(test_mae))
    print("- R2 Score: {:.4f}".format(test_r2_scr))
    r2_list.append(test_r2_scr)

    print("=" * 35)
    print("\n")

LinearRegression()
Model performance for Training set
- Root Mean Squared Error: 5.2972
- Mean Absolute Error: 4.2383
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.4825
- Mean Absolute Error: 4.3379
- R2 Score: 0.8778
===================================


Ridge()
Model performance for Training set
- Root Mean Squared Error: 5.2977
- Mean Absolute Error: 4.2371
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.4814
- Mean Absolute Error: 4.3365
- R2 Score: 0.8779
===================================


Lasso()
Model performance for Training set
- Root Mean Squared Error: 6.5469
- Mean Absolute Error: 5.1796
- R2 Score: 0.8080
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.6501
- Mean Absolute Error: 5.2184
- R2 Score: 0.8202
===================================


KNeighborsRegressor()
Model performance for Training set
- Root Mean Squared Error: 5.6662
- Mean Absolute Error: 4.5136
- R2 Score: 0.8562
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.1850
- Mean Absolute Error: 5.5624
- R2 Score: 0.7902
===================================


DecisionTreeRegressor()
Model performance for Training set
- Root Mean Squared Error: 0.2887
- Mean Absolute Error: 0.0200
- R2 Score: 0.9996
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.9413
- Mean Absolute Error: 6.1920
- R2 Score: 0.7437
===================================


RandomForestRegressor()
Model performance for Training set
- Root Mean Squared Error: 2.2849
- Mean Absolute Error: 1.8131
- R2 Score: 0.9766
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.1182
- Mean Absolute Error: 4.8107
- R2 Score: 0.8479
===================================


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)
Model performance for Training set
- Root Mean Squared Error: 0.9169
- Mean Absolute Error: 0.6051
- R2 Score: 0.9962
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.3875
- Mean Absolute Error: 5.0358
- R2 Score: 0.8342
===================================


AdaBoostRegressor()
Model performance for Training set
- Root Mean Squared Error: 5.8261
- Mean Absolute Error: 4.7722
- R2 Score: 0.8479
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.1821
- Mean Absolute Error: 4.8176
- R2 Score: 0.8447
===================================


Learning rate set to 0.039124
0:	learn: 14.5580694	total: 621us	remaining: 621ms
1:	learn: 14.1985221	total: 1.03ms	remaining: 513ms
2:	learn: 13.8301254	total: 1.51ms	remaining: 503ms
3:	learn: 13.4944939	total: 1.99ms	remaining: 495ms
4:	learn: 13.1884085	total: 2.46ms	remaining: 489ms
5:	learn: 12.8606928	total: 2.92ms	remaining: 484ms
6:	learn: 12.5739200	total: 3.39ms	remaining: 481ms
7:	learn: 12.2936989	total: 3.85ms	remaining: 477ms
8:	learn: 11.9822728	total: 4.32ms	remaining: 475ms
9:	learn: 11.7179569	total: 4.79ms	remaining: 474ms
10:	learn: 11.4699084	total: 5.25ms	remaining: 472ms
11:	learn: 11.2111621	total: 5.7ms	remaining: 469ms
12:	learn: 10.9726786	total: 6.14ms	remaining: 466ms
13:	learn: 10.7422537	total: 6.6ms	remaining: 465ms
14:	learn: 10.5374079	total: 7.05ms	remaining: 463ms
15:	learn: 10.3193891	total: 7.51ms	remaining: 462ms
16:	learn: 10.1039819	total: 8ms	remaining: 463ms
17:	learn: 9.9168135	total: 8.75ms	remaining: 477ms
18:	learn: 9.7382809	total: 9.27ms	remaining: 479ms
19:	learn: 9.5351178	total: 9.82ms	remaining: 481ms
20:	learn: 9.3656506	total: 10.3ms	remaining: 480ms
21:	learn: 9.1902150	total: 10.8ms	remaining: 478ms
22:	learn: 9.0337150	total: 11.2ms	remaining: 477ms
23:	learn: 8.8808640	total: 11.7ms	remaining: 475ms
24:	learn: 8.7365146	total: 12ms	remaining: 470ms
25:	learn: 8.5948354	total: 12.5ms	remaining: 468ms
26:	learn: 8.4607342	total: 12.9ms	remaining: 466ms
27:	learn: 8.3244046	total: 13.4ms	remaining: 465ms
28:	learn: 8.1882247	total: 13.8ms	remaining: 464ms
29:	learn: 8.0881303	total: 14.3ms	remaining: 462ms
30:	learn: 7.9578557	total: 14.7ms	remaining: 461ms
31:	learn: 7.8412445	total: 15.2ms	remaining: 460ms
32:	learn: 7.7203312	total: 15.7ms	remaining: 459ms
33:	learn: 7.6334626	total: 16.1ms	remaining: 458ms
34:	learn: 7.5320477	total: 16.6ms	remaining: 457ms
35:	learn: 7.4443704	total: 17ms	remaining: 456ms
36:	learn: 7.3409255	total: 17.5ms	remaining: 455ms
37:	learn: 7.2469453	total: 17.8ms	remaining: 452ms
38:	learn: 7.1639173	total: 18.3ms	remaining: 451ms
39:	learn: 7.0772996	total: 18.8ms	remaining: 450ms
40:	learn: 6.9920707	total: 19.2ms	remaining: 450ms
41:	learn: 6.9224311	total: 19.7ms	remaining: 449ms
42:	learn: 6.8595631	total: 20.1ms	remaining: 448ms
43:	learn: 6.7864689	total: 20.6ms	remaining: 447ms
44:	learn: 6.7203737	total: 21.1ms	remaining: 448ms
45:	learn: 6.6690947	total: 21.6ms	remaining: 449ms
46:	learn: 6.6092845	total: 22.1ms	remaining: 449ms
47:	learn: 6.5460708	total: 22.6ms	remaining: 448ms
48:	learn: 6.4883380	total: 23.3ms	remaining: 452ms
49:	learn: 6.4381575	total: 23.8ms	remaining: 452ms
50:	learn: 6.3825197	total: 24.3ms	remaining: 452ms
51:	learn: 6.3265636	total: 24.8ms	remaining: 451ms
52:	learn: 6.2888482	total: 25.2ms	remaining: 450ms
53:	learn: 6.2410664	total: 25.7ms	remaining: 450ms
54:	learn: 6.1980454	total: 26.1ms	remaining: 449ms
55:	learn: 6.1588384	total: 26.6ms	remaining: 448ms
56:	learn: 6.1185362	total: 27ms	remaining: 447ms
57:	learn: 6.0765812	total: 27.6ms	remaining: 448ms
58:	learn: 6.0408164	total: 28.4ms	remaining: 452ms
59:	learn: 6.0016682	total: 28.9ms	remaining: 453ms
60:	learn: 5.9648369	total: 29.4ms	remaining: 452ms
61:	learn: 5.9331627	total: 29.8ms	remaining: 451ms
62:	learn: 5.9002259	total: 30.3ms	remaining: 450ms
63:	learn: 5.8696659	total: 30.7ms	remaining: 449ms
64:	learn: 5.8416829	total: 31.2ms	remaining: 449ms
65:	learn: 5.8170105	total: 31.7ms	remaining: 448ms
66:	learn: 5.7906615	total: 32.1ms	remaining: 447ms
67:	learn: 5.7651158	total: 32.6ms	remaining: 446ms
68:	learn: 5.7369662	total: 33ms	remaining: 445ms
69:	learn: 5.7124012	total: 33.5ms	remaining: 445ms
70:	learn: 5.6900295	total: 34ms	remaining: 445ms
71:	learn: 5.6692436	total: 34.5ms	remaining: 444ms
72:	learn: 5.6487762	total: 34.9ms	remaining: 444ms
73:	learn: 5.6270825	total: 36ms	remaining: 451ms
74:	learn: 5.6016875	total: 36.6ms	remaining: 451ms
75:	learn: 5.5828785	total: 37.4ms	remaining: 455ms
76:	learn: 5.5681983	total: 38ms	remaining: 455ms
77:	learn: 5.5449966	total: 38.5ms	remaining: 455ms
78:	learn: 5.5268874	total: 38.9ms	remaining: 454ms
79:	learn: 5.5131647	total: 39.4ms	remaining: 453ms
80:	learn: 5.4988294	total: 39.8ms	remaining: 452ms
81:	learn: 5.4807233	total: 40.3ms	remaining: 451ms
82:	learn: 5.4643275	total: 40.8ms	remaining: 450ms
83:	learn: 5.4475293	total: 41.2ms	remaining: 449ms
84:	learn: 5.4279401	total: 41.7ms	remaining: 449ms
85:	learn: 5.4139817	total: 42.1ms	remaining: 448ms
86:	learn: 5.4040081	total: 42.6ms	remaining: 447ms
87:	learn: 5.3917399	total: 43.1ms	remaining: 446ms
88:	learn: 5.3765371	total: 43.6ms	remaining: 446ms
89:	learn: 5.3645148	total: 44ms	remaining: 445ms
90:	learn: 5.3571498	total: 44.3ms	remaining: 443ms
91:	learn: 5.3446010	total: 44.9ms	remaining: 443ms
92:	learn: 5.3337908	total: 45.4ms	remaining: 443ms
93:	learn: 5.3286915	total: 45.8ms	remaining: 441ms
94:	learn: 5.3157247	total: 46.2ms	remaining: 441ms
95:	learn: 5.3067245	total: 46.7ms	remaining: 440ms
96:	learn: 5.2939909	total: 47.2ms	remaining: 439ms
97:	learn: 5.2857495	total: 47.6ms	remaining: 438ms
98:	learn: 5.2765298	total: 48.1ms	remaining: 437ms
99:	learn: 5.2644640	total: 48.5ms	remaining: 437ms
100:	learn: 5.2513670	total: 49.2ms	remaining: 438ms
101:	learn: 5.2434087	total: 49.7ms	remaining: 438ms
102:	learn: 5.2369666	total: 50.3ms	remaining: 438ms
103:	learn: 5.2293285	total: 51.4ms	remaining: 443ms
104:	learn: 5.2216837	total: 53.3ms	remaining: 454ms
105:	learn: 5.2115154	total: 53.9ms	remaining: 454ms
106:	learn: 5.2059024	total: 54.4ms	remaining: 454ms
107:	learn: 5.1972408	total: 54.9ms	remaining: 453ms
108:	learn: 5.1881101	total: 56ms	remaining: 458ms
109:	learn: 5.1816781	total: 57.1ms	remaining: 462ms
110:	learn: 5.1723935	total: 57.7ms	remaining: 462ms
111:	learn: 5.1639866	total: 58.2ms	remaining: 461ms
112:	learn: 5.1547050	total: 58.6ms	remaining: 460ms
113:	learn: 5.1495244	total: 59.1ms	remaining: 459ms
114:	learn: 5.1446618	total: 59.5ms	remaining: 458ms
115:	learn: 5.1401118	total: 59.9ms	remaining: 457ms
116:	learn: 5.1353387	total: 60.3ms	remaining: 455ms
117:	learn: 5.1283719	total: 60.8ms	remaining: 454ms
118:	learn: 5.1236789	total: 62.6ms	remaining: 463ms
119:	learn: 5.1168919	total: 63.2ms	remaining: 464ms
120:	learn: 5.1109123	total: 63.7ms	remaining: 463ms
121:	learn: 5.1059257	total: 64.2ms	remaining: 462ms
122:	learn: 5.1005096	total: 64.7ms	remaining: 461ms
123:	learn: 5.0953860	total: 65.3ms	remaining: 461ms
124:	learn: 5.0889721	total: 66.2ms	remaining: 463ms
125:	learn: 5.0845942	total: 66.7ms	remaining: 463ms
126:	learn: 5.0827872	total: 67ms	remaining: 461ms
127:	learn: 5.0788004	total: 67.5ms	remaining: 460ms
128:	learn: 5.0752889	total: 68.1ms	remaining: 460ms
129:	learn: 5.0734125	total: 68.3ms	remaining: 457ms
130:	learn: 5.0704120	total: 68.8ms	remaining: 456ms
131:	learn: 5.0629729	total: 69.3ms	remaining: 456ms
132:	learn: 5.0568373	total: 69.8ms	remaining: 455ms
133:	learn: 5.0499886	total: 70.2ms	remaining: 454ms
134:	learn: 5.0416181	total: 70.7ms	remaining: 453ms
135:	learn: 5.0400600	total: 70.9ms	remaining: 451ms
136:	learn: 5.0351723	total: 71.4ms	remaining: 450ms
137:	learn: 5.0285613	total: 71.8ms	remaining: 449ms
138:	learn: 5.0236802	total: 72.3ms	remaining: 448ms
139:	learn: 5.0176626	total: 72.9ms	remaining: 448ms
140:	learn: 5.0159229	total: 73.4ms	remaining: 447ms
141:	learn: 5.0132403	total: 73.9ms	remaining: 446ms
142:	learn: 5.0084308	total: 74.3ms	remaining: 446ms
143:	learn: 5.0051814	total: 74.8ms	remaining: 445ms
144:	learn: 5.0019402	total: 75.3ms	remaining: 444ms
145:	learn: 4.9976023	total: 75.7ms	remaining: 443ms
146:	learn: 4.9906797	total: 76.2ms	remaining: 442ms
147:	learn: 4.9856709	total: 76.6ms	remaining: 441ms
148:	learn: 4.9816288	total: 77.1ms	remaining: 440ms
149:	learn: 4.9777277	total: 77.5ms	remaining: 439ms
150:	learn: 4.9732503	total: 78ms	remaining: 438ms
151:	learn: 4.9678973	total: 78.5ms	remaining: 438ms
152:	learn: 4.9651727	total: 79ms	remaining: 437ms
153:	learn: 4.9604649	total: 79.5ms	remaining: 437ms
154:	learn: 4.9578466	total: 80.1ms	remaining: 437ms
155:	learn: 4.9504717	total: 80.6ms	remaining: 436ms
156:	learn: 4.9482814	total: 81ms	remaining: 435ms
157:	learn: 4.9458459	total: 81.5ms	remaining: 434ms
158:	learn: 4.9426878	total: 82ms	remaining: 434ms
159:	learn: 4.9363718	total: 82.5ms	remaining: 433ms
160:	learn: 4.9329971	total: 83ms	remaining: 432ms
161:	learn: 4.9300888	total: 83.6ms	remaining: 432ms
162:	learn: 4.9264036	total: 84.3ms	remaining: 433ms
163:	learn: 4.9206668	total: 84.7ms	remaining: 432ms
164:	learn: 4.9148130	total: 85.2ms	remaining: 431ms
165:	learn: 4.9109193	total: 85.7ms	remaining: 430ms
166:	learn: 4.9089912	total: 86.3ms	remaining: 431ms
167:	learn: 4.9057750	total: 86.8ms	remaining: 430ms
168:	learn: 4.9021756	total: 87.3ms	remaining: 429ms
169:	learn: 4.8984455	total: 87.7ms	remaining: 428ms
170:	learn: 4.8952253	total: 88.2ms	remaining: 428ms
171:	learn: 4.8913926	total: 88.6ms	remaining: 427ms
172:	learn: 4.8870911	total: 89.1ms	remaining: 426ms
173:	learn: 4.8823202	total: 89.5ms	remaining: 425ms
174:	learn: 4.8799375	total: 90ms	remaining: 424ms
175:	learn: 4.8757645	total: 90.5ms	remaining: 424ms
176:	learn: 4.8734557	total: 90.9ms	remaining: 423ms
177:	learn: 4.8686012	total: 91.6ms	remaining: 423ms
178:	learn: 4.8668056	total: 92ms	remaining: 422ms
179:	learn: 4.8631132	total: 92.6ms	remaining: 422ms
180:	learn: 4.8568253	total: 93.1ms	remaining: 421ms
181:	learn: 4.8541286	total: 93.7ms	remaining: 421ms
182:	learn: 4.8513751	total: 94.2ms	remaining: 420ms
183:	learn: 4.8461827	total: 94.7ms	remaining: 420ms
184:	learn: 4.8431853	total: 95.3ms	remaining: 420ms
185:	learn: 4.8407329	total: 96ms	remaining: 420ms
186:	learn: 4.8380686	total: 96.6ms	remaining: 420ms
187:	learn: 4.8341516	total: 97.1ms	remaining: 419ms
188:	learn: 4.8304368	total: 97.6ms	remaining: 419ms
189:	learn: 4.8262935	total: 98.1ms	remaining: 418ms
190:	learn: 4.8223451	total: 98.5ms	remaining: 417ms
191:	learn: 4.8184086	total: 99ms	remaining: 417ms
192:	learn: 4.8119656	total: 99.4ms	remaining: 416ms
193:	learn: 4.8077925	total: 99.9ms	remaining: 415ms
194:	learn: 4.8071177	total: 100ms	remaining: 414ms
195:	learn: 4.8058161	total: 101ms	remaining: 413ms
196:	learn: 4.8010379	total: 101ms	remaining: 412ms
197:	learn: 4.7954882	total: 102ms	remaining: 412ms
198:	learn: 4.7905495	total: 102ms	remaining: 411ms
199:	learn: 4.7879964	total: 103ms	remaining: 410ms
200:	learn: 4.7838192	total: 103ms	remaining: 409ms
201:	learn: 4.7795732	total: 103ms	remaining: 409ms
202:	learn: 4.7758971	total: 104ms	remaining: 408ms
203:	learn: 4.7710713	total: 105ms	remaining: 408ms
204:	learn: 4.7660005	total: 105ms	remaining: 407ms
205:	learn: 4.7647823	total: 105ms	remaining: 406ms
206:	learn: 4.7603357	total: 106ms	remaining: 406ms
207:	learn: 4.7583503	total: 106ms	remaining: 405ms
208:	learn: 4.7569590	total: 107ms	remaining: 405ms
209:	learn: 4.7537849	total: 108ms	remaining: 405ms
210:	learn: 4.7500141	total: 108ms	remaining: 406ms
211:	learn: 4.7479735	total: 109ms	remaining: 405ms
212:	learn: 4.7432743	total: 109ms	remaining: 404ms
213:	learn: 4.7395003	total: 110ms	remaining: 404ms
214:	learn: 4.7381203	total: 111ms	remaining: 403ms
215:	learn: 4.7357359	total: 111ms	remaining: 403ms
216:	learn: 4.7337202	total: 111ms	remaining: 402ms
217:	learn: 4.7309397	total: 112ms	remaining: 401ms
218:	learn: 4.7279241	total: 112ms	remaining: 401ms
219:	learn: 4.7243210	total: 113ms	remaining: 401ms
220:	learn: 4.7215122	total: 114ms	remaining: 401ms
221:	learn: 4.7164013	total: 114ms	remaining: 401ms
222:	learn: 4.7145255	total: 115ms	remaining: 401ms
223:	learn: 4.7084444	total: 116ms	remaining: 401ms
224:	learn: 4.7059649	total: 116ms	remaining: 400ms
225:	learn: 4.7041616	total: 117ms	remaining: 400ms
226:	learn: 4.6975527	total: 117ms	remaining: 399ms
227:	learn: 4.6931559	total: 118ms	remaining: 398ms
228:	learn: 4.6905134	total: 118ms	remaining: 398ms
229:	learn: 4.6849802	total: 119ms	remaining: 397ms
230:	learn: 4.6813114	total: 119ms	remaining: 397ms
231:	learn: 4.6795460	total: 120ms	remaining: 397ms
232:	learn: 4.6737088	total: 120ms	remaining: 396ms
233:	learn: 4.6700490	total: 121ms	remaining: 396ms
234:	learn: 4.6681094	total: 122ms	remaining: 397ms
235:	learn: 4.6638688	total: 122ms	remaining: 396ms
236:	learn: 4.6617191	total: 123ms	remaining: 396ms
237:	learn: 4.6549348	total: 124ms	remaining: 396ms
238:	learn: 4.6514448	total: 124ms	remaining: 396ms
239:	learn: 4.6487271	total: 125ms	remaining: 396ms
240:	learn: 4.6451003	total: 126ms	remaining: 395ms
241:	learn: 4.6439451	total: 126ms	remaining: 395ms
242:	learn: 4.6411197	total: 127ms	remaining: 395ms
243:	learn: 4.6371685	total: 127ms	remaining: 395ms
244:	learn: 4.6316377	total: 128ms	remaining: 394ms
245:	learn: 4.6298052	total: 129ms	remaining: 394ms
246:	learn: 4.6244267	total: 129ms	remaining: 393ms
247:	learn: 4.6222110	total: 129ms	remaining: 393ms
248:	learn: 4.6158295	total: 130ms	remaining: 392ms
249:	learn: 4.6108508	total: 131ms	remaining: 392ms
250:	learn: 4.6070913	total: 131ms	remaining: 392ms
251:	learn: 4.6060392	total: 132ms	remaining: 392ms
252:	learn: 4.6039753	total: 132ms	remaining: 391ms
253:	learn: 4.6008648	total: 133ms	remaining: 390ms
254:	learn: 4.5979785	total: 133ms	remaining: 389ms
255:	learn: 4.5966369	total: 134ms	remaining: 389ms
256:	learn: 4.5899129	total: 134ms	remaining: 388ms
257:	learn: 4.5885667	total: 135ms	remaining: 387ms
258:	learn: 4.5849558	total: 135ms	remaining: 387ms
259:	learn: 4.5832970	total: 137ms	remaining: 389ms
260:	learn: 4.5798500	total: 137ms	remaining: 388ms
261:	learn: 4.5760975	total: 138ms	remaining: 388ms
262:	learn: 4.5732460	total: 139ms	remaining: 389ms
263:	learn: 4.5702774	total: 139ms	remaining: 389ms
264:	learn: 4.5679951	total: 140ms	remaining: 388ms
265:	learn: 4.5644321	total: 141ms	remaining: 388ms
266:	learn: 4.5615843	total: 141ms	remaining: 387ms
267:	learn: 4.5594262	total: 142ms	remaining: 387ms
268:	learn: 4.5591503	total: 142ms	remaining: 386ms
269:	learn: 4.5525327	total: 143ms	remaining: 386ms
270:	learn: 4.5481530	total: 143ms	remaining: 385ms
271:	learn: 4.5459488	total: 144ms	remaining: 385ms
272:	learn: 4.5405639	total: 144ms	remaining: 384ms
273:	learn: 4.5358737	total: 145ms	remaining: 384ms
274:	learn: 4.5315574	total: 146ms	remaining: 384ms
275:	learn: 4.5292835	total: 146ms	remaining: 384ms
276:	learn: 4.5232866	total: 147ms	remaining: 384ms
277:	learn: 4.5176692	total: 148ms	remaining: 384ms
278:	learn: 4.5151734	total: 148ms	remaining: 383ms
279:	learn: 4.5122814	total: 149ms	remaining: 384ms
280:	learn: 4.5097135	total: 150ms	remaining: 384ms
281:	learn: 4.5077935	total: 151ms	remaining: 384ms
282:	learn: 4.5062383	total: 151ms	remaining: 384ms
283:	learn: 4.5014229	total: 152ms	remaining: 383ms
284:	learn: 4.4957251	total: 153ms	remaining: 383ms
285:	learn: 4.4921772	total: 153ms	remaining: 383ms
286:	learn: 4.4899110	total: 154ms	remaining: 382ms
287:	learn: 4.4880623	total: 154ms	remaining: 382ms
288:	learn: 4.4830271	total: 155ms	remaining: 381ms
289:	learn: 4.4798315	total: 155ms	remaining: 381ms
290:	learn: 4.4782320	total: 156ms	remaining: 380ms
291:	learn: 4.4760367	total: 156ms	remaining: 379ms
292:	learn: 4.4741182	total: 157ms	remaining: 379ms
293:	learn: 4.4705781	total: 157ms	remaining: 378ms
294:	learn: 4.4686693	total: 158ms	remaining: 377ms
295:	learn: 4.4656279	total: 158ms	remaining: 377ms
296:	learn: 4.4626429	total: 159ms	remaining: 376ms
297:	learn: 4.4601735	total: 159ms	remaining: 375ms
298:	learn: 4.4567650	total: 160ms	remaining: 375ms
299:	learn: 4.4541724	total: 160ms	remaining: 374ms
300:	learn: 4.4505183	total: 161ms	remaining: 373ms
301:	learn: 4.4485641	total: 161ms	remaining: 372ms
302:	learn: 4.4465945	total: 162ms	remaining: 372ms
303:	learn: 4.4436954	total: 162ms	remaining: 371ms
304:	learn: 4.4367024	total: 163ms	remaining: 370ms
305:	learn: 4.4311147	total: 163ms	remaining: 370ms
306:	learn: 4.4269967	total: 163ms	remaining: 369ms
307:	learn: 4.4249216	total: 164ms	remaining: 368ms
308:	learn: 4.4243322	total: 165ms	remaining: 368ms
309:	learn: 4.4187363	total: 165ms	remaining: 368ms
310:	learn: 4.4120694	total: 166ms	remaining: 367ms
311:	learn: 4.4094113	total: 166ms	remaining: 367ms
312:	learn: 4.4058957	total: 167ms	remaining: 367ms
313:	learn: 4.4057530	total: 168ms	remaining: 366ms
314:	learn: 4.4037518	total: 168ms	remaining: 366ms
315:	learn: 4.4012555	total: 169ms	remaining: 365ms
316:	learn: 4.3997336	total: 169ms	remaining: 365ms
317:	learn: 4.3945435	total: 170ms	remaining: 364ms
318:	learn: 4.3907222	total: 171ms	remaining: 364ms

In [21]:
for model, scr in zip(models_list, r2_list):
    print(model, scr)

LinearRegression 0.8778243107659013
Ridge 0.877873971198214
Lasso 0.8202480287428798
KNeighborsRegressor 0.7901646026811986
DecisionTreeRegressor 0.7436669677541955
RandomForestRegressor 0.847850585069027
XGBRegressor 0.8341626524925232
AdaBoostRegressor 0.8446565687845835
CatBoostRegressor 0.8536881705730431
SVR 0.7120023175761258